"""fixes for depart

Revision ID: 15a27020bfb0
Revises: 3c483651b023
Create Date: 2019-10-27 13:12:01.830951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15a27020bfb0'
down_revision = '3c483651b023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('depart_name', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name')
    )
    op.create_index(op.f('ix_depart_depart_name'), 'depart', ['depart_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_depart_depart_name'), table_name='depart')
    op.drop_table('depart')
    # ### end Alembic commands ###
