"""new db

Revision ID: 272dc846f1c0
Revises: 
Create Date: 2019-11-04 00:55:42.678392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '272dc846f1c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('depart_name', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name')
    )
    op.create_index(op.f('ix_depart_depart_name'), 'depart', ['depart_name'], unique=True)
    op.create_table('major',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('major_code', sa.String(length=12), nullable=False),
    sa.Column('major_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_major_major_code'), 'major', ['major_code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=52), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('id_major', sa.Integer(), nullable=True),
    sa.Column('id_prof', sa.Integer(), nullable=True),
    sa.Column('id_depart', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name')
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_user_name'), 'users', ['user_name'], unique=True)
    op.create_table('prof',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.Column('prof_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['major_id'], ['major.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prof_prof_name'), 'prof', ['prof_name'], unique=False)
    op.create_table('kurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.Column('prof_id', sa.Integer(), nullable=False),
    sa.Column('depart_id', sa.Integer(), nullable=False),
    sa.Column('kurs_name', sa.String(length=255), nullable=False),
    sa.Column('img_folder', sa.String(length=255), nullable=True),
    sa.Column('percent_result', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['major_id'], ['major.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prof_id'], ['prof.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kurs_kurs_name'), 'kurs', ['kurs_name'], unique=False)
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.Column('prof_id', sa.Integer(), nullable=False),
    sa.Column('kurs_id', sa.Integer(), nullable=False),
    sa.Column('q_text', sa.Text(), nullable=False),
    sa.Column('img_name', sa.String(length=255), nullable=True),
    sa.Column('answ1', sa.String(length=255), nullable=False),
    sa.Column('answ1_true', sa.SmallInteger(), nullable=False),
    sa.Column('answ2', sa.String(length=255), nullable=True),
    sa.Column('answ2_true', sa.SmallInteger(), nullable=True),
    sa.Column('answ3', sa.String(length=255), nullable=True),
    sa.Column('answ3_true', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['kurs_id'], ['kurs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['major_id'], ['major.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prof_id'], ['prof.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    op.drop_index(op.f('ix_kurs_kurs_name'), table_name='kurs')
    op.drop_table('kurs')
    op.drop_index(op.f('ix_prof_prof_name'), table_name='prof')
    op.drop_table('prof')
    op.drop_index(op.f('ix_users_user_name'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_major_major_code'), table_name='major')
    op.drop_table('major')
    op.drop_index(op.f('ix_depart_depart_name'), table_name='depart')
    op.drop_table('depart')
    # ### end Alembic commands ###
