"""new table kurs + percent

Revision ID: 64ca3a2c7600
Revises: bbf4bf04517b
Create Date: 2019-10-27 18:45:54.379840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64ca3a2c7600'
down_revision = 'bbf4bf04517b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.Column('prof_id', sa.Integer(), nullable=False),
    sa.Column('depart_id', sa.Integer(), nullable=False),
    sa.Column('kurs_name', sa.String(length=255), nullable=False),
    sa.Column('img_folder', sa.String(length=255), nullable=True),
    sa.Column('percent_result', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['major_id'], ['major.id'], ),
    sa.ForeignKeyConstraint(['prof_id'], ['prof.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kurs_kurs_name'), 'kurs', ['kurs_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kurs_kurs_name'), table_name='kurs')
    op.drop_table('kurs')
    # ### end Alembic commands ###
