"""fixes for Prof

Revision ID: bbf4bf04517b
Revises: e67bec20df86
Create Date: 2019-10-27 15:51:04.609824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbf4bf04517b'
down_revision = 'e67bec20df86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prof',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.Column('prof_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['major_id'], ['major.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prof_prof_name'), 'prof', ['prof_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prof_prof_name'), table_name='prof')
    op.drop_table('prof')
    # ### end Alembic commands ###
