"""new table question

Revision ID: c83e8637ecc6
Revises: 64ca3a2c7600
Create Date: 2019-10-27 22:45:34.315039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c83e8637ecc6'
down_revision = '64ca3a2c7600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.Column('prof_id', sa.Integer(), nullable=False),
    sa.Column('kurs_id', sa.Integer(), nullable=False),
    sa.Column('q_text', sa.Text(), nullable=False),
    sa.Column('answ1', sa.String(length=255), nullable=False),
    sa.Column('answ1_true', sa.SmallInteger(), nullable=False),
    sa.Column('answ2', sa.String(length=255), nullable=True),
    sa.Column('answ2_true', sa.SmallInteger(), nullable=True),
    sa.Column('answ3', sa.String(length=255), nullable=True),
    sa.Column('answ3_true', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['kurs_id'], ['kurs.id'], ),
    sa.ForeignKeyConstraint(['major_id'], ['major.id'], ),
    sa.ForeignKeyConstraint(['prof_id'], ['prof.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    # ### end Alembic commands ###
