"""fixes tables majors

Revision ID: e67bec20df86
Revises: 15a27020bfb0
Create Date: 2019-10-27 15:45:47.157172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e67bec20df86'
down_revision = '15a27020bfb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('major',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('major_code', sa.String(length=12), nullable=False),
    sa.Column('major_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_major_major_code'), 'major', ['major_code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_major_major_code'), table_name='major')
    op.drop_table('major')
    # ### end Alembic commands ###
